import React from 'react'
import { cn } from 'src/utilities/cn'

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  description: 'Generated by Next.js',
  title: 'Next.js',
}

// eslint-disable-next-line no-restricted-exports
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={cn(inter.className, 'min-h-screen bg-background')}>
      <body suppressHydrationWarning>{children}</body>
    </html>
  )
}
